# Generated by Django 3.0.1 on 2020-01-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='text',
            field=models.CharField(max_length=30000),
        ),
    ]
