# Generated by Django 3.0.1 on 2020-01-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='message',
            field=models.FileField(upload_to=''),
        ),
    ]
